### ISSUE TITLE
Mobile Device

### ISSUE THREAD

**Issue by AKMourato** [iArunava/ENet-Real-Time-Semantic-Segmentation#10]
Hello Arunava,

Congrats for the work.

Can you please tell me how can I deploy this model for real time segmentation on mobile?

Thank you
Regards

**Comment by AvivSham** [comment]
Hi @mourasftw 
please see the attached tutorial. It will help you.
https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html
