### ISSUE TITLE
@AvivSham Thank you for your reply! Not the test  image. The image I am using is in jpg format and the image size is 266*200.I didn't train the new model, I used the model you provided.I modified your code.

### ISSUE THREAD

**Issue by JeremyLinky** [iArunava/ENet-Real-Time-Semantic-Segmentation#12]
@AvivSham Thank you for your reply! Not the test  image. The image I am using is in jpg format and the image size is 266*200.I didn't train the new model, I used the model you provided.I modified your code.
Like this:
![image](https://user-images.githubusercontent.com/38452175/53715067-9c969000-3e8b-11e9-93e5-1c293a020c26.png)

I just used the images in the Camvid dataset, which is the result.
![image](https://user-images.githubusercontent.com/38452175/53715254-2e060200-3e8c-11e9-90fb-32120ed0d967.png)
But the class is not right, from the color point of view

_Originally posted by @zhouzhubin in https://github.com/iArunava/ENet-Real-Time-Semantic-Segmentation/issues/3#issuecomment-469137452_

**Comment by JeremyLinky** [comment]
你好，你是怎么把道路的颜色从绿色变成红色的呢@zhouzhubin

**Comment by AvivSham** [comment]
Did you convert the images from BRG to RGB? in case you have read the images using opencv
