### ISSUE TITLE
What about a pretrained model?

### ISSUE THREAD

**Issue by marisna** [iArunava/ENet-Real-Time-Semantic-Segmentation#13]
Hi, 
Thanks a lot for your work!
I was just wondering : what about a pretrained model to be able to faster run inferences and get a preview of the performances? 
Best wishes for your work !

**Comment by marisna** [comment]
sorry i wrote too fast... for future reader, the pretrained model is at datasets/CamVid/

**Comment by ghost** [comment]
seems the pre-trained model has been removed. @iArunava possible to upload a new one? Helpful in getting started...

**Comment by AvivSham** [comment]
We removed it because there was a problem with the implementation, you can train a new model using the published notebook.
