### ISSUE TITLE
Size mismatch for fullconv.weight

### ISSUE THREAD

**Issue by lccatala** [iArunava/ENet-Real-Time-Semantic-Segmentation#21]
Hi,

When testing a model I trained myself it gives me the following error:
`Traceback (most recent call last):
  File "init.py", line 153, in <module>
    test(FLAGS)
  File "/home/alpasfly/tfg/ENet-Real-Time-Semantic-Segmentation/test.py", line 24, in test
    enet.load_state_dict(checkpoint['state_dict'])
  File "/home/alpasfly/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ENet:
	size mismatch for fullconv.weight: copying a param with shape torch.Size([16, 102, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 12, 3, 3]).
`
I saw [a closed Issue](https://github.com/iArunava/ENet-Real-Time-Semantic-Segmentation/issues/9) with the same problem and it appeared to be solved, but appearently it isn't. Any suggestions?

Thanks in advance.

**Comment by AvivSham** [comment]
There is a mismatch between the weights you saved and the model you initialized. Did you initialize your model the same way as you did before training?

**Comment by lccatala** [comment]
It seemed to be a problem in test.py. The Enet class is constructed with 12 classes instead of 102 (I can make a pull request for that if you want). The error message when running on test mode now is
```
RuntimeError: All input tensors must be on the same device. Received cpu and cuda:0
```

**Comment by AvivSham** [comment]
I fixed the issue now the model is initialized with the number of classes passed as an argument.
```model=Enet(FLAGS.num_classes)```
pull and try.

**Comment by lccatala** [comment]
Yes, I saw it 3 hours late, sorry.

About the other issue, I've found that these changes to test.py made it work
```
import torch
import torch.nn as nn
from utils import *
from models.ENet import ENet
import sys
import os
from tqdm import tqdm
import matplotlib.pyplot as plt


def test(FLAGS):
    # Check if the pretrained model is available
    if not FLAGS.m.endswith('.pth'):
        raise RuntimeError('Unknown file passed. Must end with .pth')
    if FLAGS.image_path is None or not os.path.exists(FLAGS.image_path):
        raise RuntimeError('An image file path must be passed')
    
    h = FLAGS.resize_height
    w = FLAGS.resize_width

    checkpoint = torch.load(FLAGS.m,  map_location=FLAGS.cuda)
    
    # Assuming the dataset is camvid
    enet = ENet(FLAGS.num_classes)
    enet.load_state_dict(checkpoint['state_dict'])
    enet.cuda()

    tmg_ = plt.imread(FLAGS.image_path)
    tmg_ = cv2.resize(tmg_, (h, w), cv2.INTER_NEAREST)
    tmg = torch.tensor(tmg_).unsqueeze(0).float()
    tmg = tmg.transpose(2, 3).transpose(1, 2).to(FLAGS.cuda)

    with torch.no_grad():
        out1 = enet(tmg.float()).squeeze(0)
    
    #smg_ = Image.open('/content/training/semantic/' + fname)
    #smg_ = cv2.resize(np.array(smg_), (512, 512), cv2.INTER_NEAREST)

    b_ = out1.data.max(0)[1].cpu().numpy()

    decoded_segmap = decode_segmap(b_)

    images = {
        0 : ['Input Image', tmg_],
        1 : ['Predicted Segmentation', b_],
    }

    show_images(images)

```

**Comment by AvivSham** [comment]
I didn't understand what you changed but if it works it works 👍 . 
I guess you were trying to use gpu, if that is the case then you should assign both data and model on the same device.
