### ISSUE TITLE
Using with other datasets

### ISSUE THREAD

**Issue by lccatala** [iArunava/ENet-Real-Time-Semantic-Segmentation#23]
Hi, I'm trying to train your model with the Cityscapes dataset, however the function get_class_weights returns an array of size 34 (so, 34 class weights), while the dataset only contains 19 classes. Are we supposed to change anything to make this work with other datasets?

Thanks in advance

**Comment by Abdul-Nasir11** [comment]
get_class_weights takes (nc = number of channels) you should change it to 19.. 
you should also change the color_map according to your dataset
