### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ENet:

### ISSUE THREAD

**Issue by ayushmankumar7** [iArunava/ENet-Real-Time-Semantic-Segmentation#25]
Traceback (most recent call last):
  File "init.py", line 153, in <module>
    test(FLAGS)
  File "/media/ayushman/Seagate Expansion Drive/DeepLearning - Repos/TESTING/ENet-Real-Time-Semantic-Segmentation/test.py", line 27, in test
    enet.load_state_dict(checkpoint['state_dict'])
  File "/home/ayushman/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ENet:
	Missing key(s) in state_dict: "b10.batchnorm1.weight", "b10.batchnorm1.bias", "b10.batchnorm1.running_mean", "b10.batchnorm1.running_var", "b10.batchnorm3.weight", "b10.batchnorm3.bias", "b10.batchnorm3.running_mean", "b10.batchnorm3.running_var", "b11.batchnorm1.weight", "b11.batchnorm1.bias", "b11.batchnorm1.running_mean", "b11.batchnorm1.running_var", "b11.batchnorm3.weight", "b11.batchnorm3.bias", "b11.batchnorm3.running_mean", "b11.batchnorm3.running_var", "b12.batchnorm1.weight", "b12.batchnorm1.bias", "b12.batchnorm1.running_mean", "b12.batchnorm1.running_var", "b12.batchnorm3.weight", "b12.batchnorm3.bias", "b12.batchnorm3.running_mean", "b12.batchnorm3.running_var", "b13.batchnorm1.weight", "b13.batchnorm1.bias", "b13.batchnorm1.running_mean", "b13.batchnorm1.running_var", "b13.batchnorm3.weight", "b13.batchnorm3.bias", "b13.batchnorm3.running_mean", "b13.batchnorm3.running_var", "b14.batchnorm1.weight", "b14.batchnorm1.bias", "b14.batchnorm1.running_me....

**Comment by AvivSham** [comment]
did you train the model from scratch?

**Comment by AvivSham** [comment]
the issue is closed (if the problem still exists please reopen)
