### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by vcvishal** [iArunava/ENet-Real-Time-Semantic-Segmentation#9]
this error occurred when I ran the test

C:\Users\vcvis\Desktop\ENet-Real-Time-Semantic-Segmentation-master>python init.py --mode test -m ckpt-enet-10-379.48720532655716.pth -i 0006R0_f01320.png
Traceback (most recent call last):
  File "init.py", line 153, in <module>
    test(FLAGS)
  File "C:\Users\vcvis\Desktop\ENet-Real-Time-Semantic-Segmentation-master\test.py", line 24, in test
    enet.load_state_dict(checkpoint['state_dict'])
  File "D:\miniconda\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ENet:
        size mismatch for fullconv.weight: copying a param with shape torch.Size([16, 102, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 12, 3, 3]).

guide me 
thank you

**Comment by iArunava** [comment]
Check now, it shouldn't be the case. Clone the repo with all the updated changes. If this is solved, please close the issue.
